#!/bin/bash
set -euo pipefail

declare -A xdg_symlinks misc_symlinks

xdg_symlinks=(
  ['syncthing']='/data/syncthing'
  ['chromium']='/data/browser/chromium'
  ['unity3d']='/extra/games/unity3d'
  ['gh/hosts.yml']='/data/github/hosts.yml'
  ['spotifyd']='/data/spotify/daemon'
  ['spotify-tui']='/data/spotify/tui'
  ['spotify']='/data/spotify/desktop'
  ['Signal']='/data/social/signal'
  ['Slack']='/data/social/slack'
  ['discord']='/data/social/discord'
  ['cargo-aoc']='/data/social/cargo-aoc'
  ['rmapi']='/data/rmapi'
  ['rmcl']='/data/rmcl'
  ['tentactl']='/data/tentactl'
  ['khal']='/data/khal'

  ['spotify-player']='../dotfiles/vic/spotify-player'
  ['xmonad']='../dotfiles/desk/xmonad'
  ['awesome']='../dotfiles/desk/awesome'
  ['penrose']='../dotfiles/desk/penrose'
  ['bspwm']='../dotfiles/desk/bspwm'
  ['sxhkd']='../dotfiles/desk/sxhkd'

  ['river']='../dotfiles/common/river'
  ['foot']='../dotfiles/common/foot'
  ['waybar']='../dotfiles/common/waybar'
  ['kanshi']='../dotfiles/boi/kanshi'

  ['nix']='../dotfiles/common/nix'

  ['taffybar']='../dotfiles/desk/taffybar'
  ['polybar']='../dotfiles/desk/polybar'

  ['picom']='../dotfiles/desk/picom'
  ['autorandr']='../dotfiles/desk/autorandr'
  ['rofi']='../dotfiles/desk/rofi'
  ['conky']='../dotfiles/desk/conky'
  ['zathura']='../dotfiles/desk/zathura'
  ['xournalpp']='../dotfiles/desk/xournalpp'

  ['kitty']='../dotfiles/desk/kitty'
  ['alacritty']='../dotfiles/desk/alacritty'
  ['wezterm']='../dotfiles/desk/wezterm'
  ['xdg']='../dotfiles/desk/xdg'
  ['mpv']='../dotfiles/desk/mpv'

  ['spotify-player']='../dotfiles/common/spotify-player'
)

misc_symlinks=(
  ['dotfiles']='/data/dotfiles'
  ['documents']='/data/documents'
  ['hacks']='/data/hacks'
  ['downloads']='/extra/downloads'
  ['pictures']='/extra/media/pictures'
  ['videos']='/extra/media/videos'
  ['music']='/extra/media/music'
  ['blinc']='/extra/blinc'

  ['.thunderbird']='/data/social/thunderbird'
  ['.zoom']='/data/social/zoom'
  ['.mozilla/firefox']='/data/browser/firefox'
  ['.gnupg']='/data/gnupg'
  ['.password-store']='/data/pass'
  ['.Mathematica']='/data/mathematica'
  ['.cache/Tectonic']='/data/tectonic'
  ['.local/share/zathura']='/data/zathura'
  ['.local/share/TelegramDesktop']='/data/social/telegram'
  ['.local/share/Celeste']='/extra/games/celeste'

  ['.klei']='/extra/games/klei'
  ['.multimc']='/extra/games/multimc'
  ['.steam']='/extra/games/steam/home'
  ['.local/share/Steam']='/extra/games/steam/share'
  ['.local/share/PrismLauncher']='/extra/games/prism-mc'
  ['.local/share/UnrailedGame']='/extra/games/unrailed'

  ['.local/share/lutris']='/extra/games/lutris/share'
  ['.config/lutris']='/extra/games/lutris/config'

  ['.local/share/containers']='/extra/containers/kshi'

  ['.netrc']='/data/login/netrc'

  ['.xsession']='dotfiles/desk/xsession'

  # TODO nix stuff: .nix-channels .nix-profile .nix-defexpr

)

for link in "${!xdg_symlinks[@]}"; do
  buildah run "$1" -- mkdir -p "$(dirname ".config/$link")"
  buildah run "$1" -- ln -sT "${xdg_symlinks[$link]}" ".config/$link"
done

for link in "${!misc_symlinks[@]}"; do
  buildah run "$1" -- mkdir -p "$(dirname "$link")"
  buildah run "$1" -- ln -sT "${misc_symlinks[$link]}" "$link"
done
