#!/bin/bash
set -eufo pipefail

buildah run "$1" rustup-init -qy -c 'rust-src' 'rust-analyzer'

# build broken for both
#buildah run "$1" .cargo/bin/cargo install --git 'https://github.com/kamadorueda/alejandra' --tag '3.0.0'

# seems to require invoking `nix` during build?
# buildah run "$1" .cargo/bin/cargo install \
#   --git 'https://github.com/oxalica/nil' \
#   --tag '2023-08-09' \
#   'nil'
