#!/bin/bash
set -eufo pipefail

declare -a pkgs=(

  'typescript'
  'ttypescript'

  'prettier'
  'eslint'
  'typescript-language-server'

  '@elm-tooling/elm-language-server'
  'elm-format'
  'elm-test'

  'svelte-language-server'

  'netlify-cli'
  'vercel'

  'pyright'

  'neovim'

)

buildah run "$1" -- pnpm add -C '.pnpm-global' "${pkgs[@]}"
