#!/bin/bash
set -eufo pipefail

declare -a pkgs=(

  'typescript'
  'ttypescript'
  'ts-node'

  'prettier'
  'eslint'
  'typescript-language-server'

  '@elm-tooling/elm-language-server'
  'elm-format'
  'elm-test'

  'svelte-language-server'
  'prettier-plugin-svelte'

  'vls'
  '@volar/vue-language-server'

  'heroku' # TODO make into package
  'netlify-cli'
  'vercel'

  'pyright'

  'neovim'

)

buildah run "$1" -- pnpm add -C '.pnpm-global' "${pkgs[@]}"
