#!/bin/bash
set -eufo pipefail

declare -a pkgs=(
  'black'

  'python-lsp-server'
  'python-lsp-black'
  'pylsp-mypy'
  'pyls-isort'
  #'python-language-server'
  #'pyls-black'
  #'pyls-mypy'
  #'future' # needed by 'pyls-mypy'

  'matplotlib'
  'numpy'
  'scipy'
  'sympy'
  'gmpy2'
  'mpmath'

  'pandas'
  'bokeh'
  'seaborn'

  'torch'

  'ipython'

  'pynvim'
)

buildah run "$1" virtualenv '.venv'
if [[ -e ~/'.cache/pip' ]]; then
  buildah copy --chown 'kshi:kshi' "$1" ~/'.cache/pip' '.cache/pip'
fi
buildah run "$1" .venv/bin/pip install "${pkgs[@]}"
