#!/bin/bash
set -eufo pipefail

declare -a pkgs=(
  'black'
  'build'

  'pillow'

  'python-lsp-server'
  'python-lsp-black'
  'pylsp-mypy'
  'pyls-isort'
  #'python-language-server'
  #'pyls-black'
  #'pyls-mypy'
  #'future' # needed by 'pyls-mypy'
  'pytest'
  'pytest-benchmark'
  'hypothesis'

  #'taichi'

  'flask'
  'beautifulsoup4'
  'requests'
  'aiohttp'

  'pyperclip'

  'matplotlib'
  'numpy'
  'scipy'
  'sympy'
  #'gmpy2'
  'mpmath'

  'pandas'
  'pandas-stubs'
  'bokeh'
  'seaborn'

  'opencv-python'

  # 'torch==1.9.1'
  'scikit-learn'
  #'scikit-image'

  'more-itertools'

  'ipython'
  'pyside2' # needed by qtconsole, but weirdly not installed as dep
  'qtconsole'


  'pynvim'
)

buildah run "$1" virtualenv '.venv'
if [[ -e ~/'.cache/pip' ]]; then
  buildah copy -q --chown 'kshi:kshi' "$1" ~/'.cache/pip' '.cache/pip'
fi
buildah run "$1" .venv/bin/pip install "${pkgs[@]}"
