#!/bin/bash
set -euo pipefail

if [[ -e ~/'.texlive2021/texmf-var/luatex-cache' ]]; then
  buildah copy -q --chown 'kshi:kshi' "$1" \
    ~/'.texlive2021/texmf-var/luatex-cache' '.texlive2021/texmf-var/luatex-cache'
fi
