root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/blinc-server"
  args_bin = ['start']
  cmd = "go build -o ./tmp/blinc-server ./cmd/blinc-server"
  delay = 1000
  exclude_dir = ['tmp', 'vendor', 'ui']
  send_interrupt = true

[log]
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
