#!/bin/bash
set -eufo pipefail

declare -a pkgs=(
  'penlight'
  'inspect'
  'http'
  'luasocket'
  'htmlparser'

  'fennel'
  'tl'
)

for pkg in "${pkgs[@]}"; do
  buildah run "$1" luarocks install --local "$pkg"
done
