#!/bin/bash
set -euo pipefail

# vi: ft=bash
# shellcheck shell=bash

declare nvim_dir autoload_dir plug_dir
nvim_dir='.local/share/nvim/site'
autoload_dir="$nvim_dir/autoload"
plug_dir="$nvim_dir/plug"

declare -a pkgs
pkgs=(

  'rktjmp/hotpot.nvim'
  'bakpakin/fennel.vim'
  'Olical/conjure'

  'glepnir/lspsaga.nvim'

  'gruvbox-community/gruvbox'

  'preservim/nerdtree'
  'junegunn/fzf'
  'junegunn/fzf.vim'
  'neovim/nvim-lspconfig'
  'nvim-treesitter/nvim-treesitter'
  #'nvim-lua/completion-nvim'
  #'norcalli/nvim-colorizer.lua'

  'rrethy/vim-hexokinase'
  'psliwka/vim-smoothie'

  'prettier/vim-prettier'

  'kana/vim-textobj-user'
  'glts/vim-textobj-comment'

  'JuliaEditorSupport/julia-vim'
  'evanleck/vim-svelte'
  'cespare/vim-toml'
  'vmchale/just-vim'
  'lervag/vimtex'

  'SirVer/ultisnips'
  #'honza/vim-snippets'

  'lilydjwg/fcitx.vim'

  'ntpeters/vim-better-whitespace'

  'dense-analysis/ale'
  'nvim-lua/lsp-status.nvim'

  'sirtaj/vim-openscad'

  'jreybert/vimagit'
  'tpope/vim-fugitive'
  'kdheepak/lazygit.nvim'

  'nvim-telescope/telescope.nvim'

  'mattn/emmet-vim'

  'ziglang/zig.vim'

  'psf/black'

  'chrisbra/unicode.vim'

  'nvim-orgmode/orgmode'

  'nvim-lua/plenary.nvim'
  'jose-elias-alvarez/null-ls.nvim'
  'jose-elias-alvarez/typescript.nvim'
  'MunifTanjim/eslint.nvim'

  'rhysd/vim-clang-format'

  'kyazdani42/nvim-web-devicons'
  'tbastos/vim-lua'
  'glacambre/firenvim'
  'folke/trouble.nvim'

  'L3MON4D3/LuaSnip'

  'wuelnerdotexe/vim-astro'

)

buildah run "$1" -- mkdir -p "$autoload_dir" "$plug_dir"

buildah add "$1" \
  'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim' \
  "$autoload_dir/plug.vim"

buildah copy "$1" \
  'home/neovim/file/firenvim-firefox.json' \
  '.mozilla/native-messaging-hosts/firenvim.json'

buildah copy --chmod 744 "$1" \
  'home/neovim/file/firenvim-script.sh' \
  '.local/share/firenvim/firenvim'

for repo in "${pkgs[@]}"; do
  buildah run "$1" git clone "https://github.com/$repo" "$plug_dir/${repo##*/}"
done

buildah run "$1" make -C "$plug_dir/vim-hexokinase" hexokinase
