#!/bin/bash
. 'script/lib'

out="$BUILD_DIR/out/$1"

log 'copying squashfs image'
cp -r "$out/squash.img" "/run/initramfs/live/void-$1.img"

log 'copying boot configuration'
cp "$out/boot.conf" "/efi/loader/entries/void-$1.conf"

log 'copying linux boot files'
cp -r "$out/linux" "/efi/linux/void/$1"

log 'updating default boot entry'
readarray -t conf < '/efi/loader/loader.conf'
for line in "${conf[@]}"; do
  if [[ "${line%% *}" == 'default' ]]; then
    echo "default void-$1"
  else
    echo "$line"
  fi
done > '/efi/loader/loader.conf'
