#!/bin/bash
. 'script/lib'

declare -a pkgs lists
declare name

function phase_img_pkgs {
  log 'loading packages'
  pkgs=()
  while read -r line; do
    line="${line%%#*}"
    read -ra ps <<< "$line"
    for pkg in "${ps[@]}"; do pkgs+=("$pkg"); done
  done < "$ROOT_DIR/pkgs/$name"
  log "loaded, ${#pkgs[@]} packages"

  buildah run "$1" -- xbps-install -y "${pkgs[@]}"
}

lists=("$ROOT_DIR/pkgs"/*)
for (( i = 0; i < ${#lists[@]}; ++i )); do
  name="${lists[i]##*/}"
  if [[ $i == 0 ]]; then prev='base'; else prev="pkgs/${lists[i-1]##*/}"; fi
  phase_img "pkgs/$name" 'phase_img_pkgs' \
    "$prev" "$(stat -c '%Y' "$ROOT_DIR/pkgs/$name")"
done

log_phase 'img/pkgs'
log "tagging alias for final image: ${name@Q}"
buildah tag "$BUILDAH_NAME_PREFIX/pkgs/$name" "$BUILDAH_NAME_PREFIX/pkgs"
log_done 'img/pkgs'
