#!/bin/bash
set -euo pipefail

declare -a extensions=(
  'ms-vsliveshare.vsliveshare'
  'tomphilbin.gruvbox-themes'
  #'asvetliakov.vscode-neovim'

  'astro-build.astro-vscode'
)

for ext in "${extensions[@]}"; do
  buildah run "$1" -- code-oss --install-extension "$ext"
done
