#!/bin/bash
set -eufo pipefail

declare -a pkgs=(
  'hspec'
  'hspec-discover'
  'QuickCheck'
)

buildah run "$1" ghcup install 'ghc'
buildah run "$1" ghcup install 'cabal'
buildah run "$1" ghcup install 'hls'
buildah run "$1" ghcup install 'stack'

buildah run "$1" ghcup set 'ghc'
buildah run "$1" ghcup set 'cabal'
buildah run "$1" ghcup set 'hls'
buildah run "$1" ghcup set 'stack'

buildah run "$1" -- mkdir -p '.stack'
buildah run "$1" -- hoogle generate

buildah run "$1" -- ln -s '../dotfiles/cli/stack/config.yaml'

#buildah run "$1" cabal install --lib "${pkgs[@]}"
