#!/bin/bash -eu

bspc config border_width 2
bspc config window_gap 4
bspc config focused_border_color '#b8bb26'
bspc config active_border_color '#79740e'
bspc config normal_border_color '#32302f'
bspc config pointer_follows_focus true

sxhkd -m -1 &

redshift &

alacritty &

bspc monitor DisplayPort-1 -d main{1..5}
bspc monitor HDMI-A-0 -d tab{1..5}

bspc rule -a zathura state=tiling

for disp in main tab; do 
  for pos in top bottom; do 
    polybar -r $disp-$pos &
  done
done

