#!/bin/bash

bspc config border_width 2
bspc config window_gap 4
bspc config focused_border_color '#b8bb26'
bspc config active_border_color '#79740e'
bspc config normal_border_color '#1d2021'

hsetroot -add '#32302f' -add '#689d6a' -gradient 0
sct 3000

sxhkd -m -1 &

picom &

alacritty &


bspc monitor DisplayPort-1 -d main{1..5}
bspc monitor HDMI-A-0 -d tab{1..5}

bspc rule -a zathura state=tiling

for disp in main tab; do 
  for pos in top bottom; do 
    polybar -r $disp-$pos &
  done
done

